#!/bin/bash


# to maintain cask ....
#     brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup`


# Install native apps

brew install caskroom/cask/brew-cask
brew tap caskroom/versions


# Env
#brew cask install java
#brew cask install java8

brew cask install alfred



# Dev tool
brew cask install iterm2
#brew cask install atom
brew cask install macvim
brew cask install sourcetree
brew cask install visual-studio-code
#brew cask install sqlitestudio
#brew cask install webstorm
#brew cask install intellij-idea
#brew cask install charles
#brew cask install cyberduck
#brew cask install mysqlworkbench
brew cask install macdown

# apps

brew cask install google-chrome
brew cask install google-chrome-canary
brew cask install firefox
#brew cask install bettertouchtool
#brew cask install macid
brew cask install slack
brew cask install evernote
brew cask install dropbox

# brew cask install istat-menus
brew cask install go2shell
#brew cask install flycut
#brew cask install xmind
#brew cask install tunnelblick
#brew cask install flycut
brew cask install wechat
#brew cask install Kitematic 
#brew cask install gemini
#brew cask install cheatsheet
brew cask install pgadmin4




