# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
#ZSH_THEME="arrow"
#ZSH_THEME="juanghurtado"
##ZSH_THEME="kphoen"
#ZSH_THEME="sporty_256"
#

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

#aliases
alias mkdir='mkdir -pv'
alias rm='rm -rf'
alias reload='source ~/.zshrc'
alias count='find . -name "*" | xargs wc -l'
alias tracker='cp /Users/ericwu/Development/Yieldmo-Porjects/tld/tracker/target/scala-2.9.2/tracker_2.9.2-prebuild.war /var/lib/tomcat/libexec/webapps/tracker.war'

#hash
setopt autocd
hash -d dev=$HOME/Development
hash -d y=$HOME/Development/Yieldmo-Porjects
hash -d tld=$HOME/Development/Yieldmo-Porjects/tld
hash -d cfg=$HOME/Development/Yieldmo-Porjects/cfg
hash -d admin=$HOME/Development/Yieldmo-Porjects/admin-frontend
hash -d af=$HOME/Development/Yieldmo-Porjects/af/af-frontend
hash -d temp=$HOME/Development/temp 
hash -d my=$HOME/Development/my-project 
hash -d tom=/var/lib/tomcat/libexec
hash -d tomcat=/var/lib/tomcat/libexec
hash -d meoge=$HOME/Development/temp/website/meoge


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


export PATH="$PATH:$HOME/Development/my-project/git-command/"

##MY FUNCTIONS
# Create a new directory and enter it
function mkd() {
	mkdir -p "$@" && cd "$_";
}
function qa() {
    ~/Development/Yieldmo-Porjects/dev-scripts/claim_qa_portal.sh qa-admin-01
    ~/Development/Yieldmo-Porjects/dev-scripts/claim_qa_portal.sh qa-admin-02
    ~/Development/Yieldmo-Porjects/dev-scripts/claim_qa_portal.sh qa-admin-03
}
function qa3(){
    ~/Development/Yieldmo-Porjects/dev-scripts/claim_qa_portal.sh qa-admin-03
}


[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh


function fixgit() {
    find . -type f -name config -exec sed -ie 's/gitlab.aws.in.yieldmo.com/gitlab.yieldmo.com/g' {} +
}

function hyper(){
    grunt preview --target=35_hyperplay
    grunt watch --target=35_hyperplay
}

function win(){
    grunt preview --target=34_windowplay 
    grunt watch --target=34_windowplay 
}

function setf(){
    rm -f $HOME/Development/Yieldmo-Porjects/af-frontend/bower_components/ym-formats/formats.js
    ln -s $HOME/Development/Yieldmo-Porjects/web-formats/dist/formats.js $HOME/Development/Yieldmo-Porjects/af-frontend/bower_components/ym-formats/formats.js
}
function setym(){
    ln -s ~/Development/Yieldmo-Porjects/sdk-js/dist/publisher/ym/ym.concat.js ~/Development/Yieldmo-Porjects/web-formats/preview/ym.min.js
}
function init-project(){
    bower i
    npm i
    grunt
}

#  ### compress video file
#  ffmpeg -i video.mp4 -b 140k  video7.mp4
#  ffmpeg -i video.mp4 -s 640x480 -b 512k -vcodec mpeg1video -acodec copy video1.mp4


[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
