#!/bin/bash

# Exit on any error
set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

echo "Starting Template Preparation..."
echo "WARNING: This will clean sensitive data and prepare VM for templating"

# Check if running in a pipe (non-interactive)
if [ -t 0 ]; then
    read -p "Continue? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
else
    echo "Running in non-interactive mode (piped from curl)"
    echo "Proceeding automatically in 5 seconds... Press Ctrl+C to cancel"
    sleep 5
fi

# 1. Update the System
echo "--- Updating System Packages ---"
apt update && apt upgrade -y

# 2. Install Essential Tools & Apply OS-Specific Fixes
echo "--- Installing Cloud-Init and QEMU Guest Agent ---"
apt install -y cloud-init qemu-guest-agent

# Detect OS
source /etc/os-release
if [[ "$ID" == "debian" ]]; then
    echo "--- Debian Detected: Installing resolvconf for Static IP DNS fix ---"
    # Debian needs these to handle Cloud-Init networking correctly without Netplan
    apt install -y resolvconf ifupdown
    
    # SAFETY NET: Ensure /etc/network/interfaces exists so ifupdown doesn't crash
    touch /etc/network/interfaces
    
    systemctl enable resolvconf
elif [[ "$ID" == "ubuntu" ]]; then
    echo "--- Ubuntu Detected: Skipping resolvconf (relies on Netplan/systemd-resolved) ---"
else
    echo "--- Unknown OS: $ID. Proceeding with standard tools only ---"
fi

systemctl enable qemu-guest-agent

# 2b. Disable Predictable Network Interface Names
echo "--- Disabling Predictable Network Interface Names ---"
# This ensures network interfaces are always named eth0, eth1, etc.
# instead of ens18, ens19, etc. (which depend on PCI slot)
# This provides consistent naming across VM templates and clones
if grep -q 'GRUB_CMDLINE_LINUX=' /etc/default/grub; then
    # Check if net.ifnames is already set
    if ! grep -q 'net.ifnames=0' /etc/default/grub; then
        sed -i 's/GRUB_CMDLINE_LINUX="\(.*\)"/GRUB_CMDLINE_LINUX="\1 net.ifnames=0 biosdevname=0"/' /etc/default/grub
        # Clean up any double spaces
        sed -i 's/GRUB_CMDLINE_LINUX=" /GRUB_CMDLINE_LINUX="/' /etc/default/grub
        update-grub
        echo "Predictable network names disabled (will take effect after reboot)"
    else
        echo "Predictable network names already disabled"
    fi
else
    echo "WARNING: Could not find GRUB_CMDLINE_LINUX in /etc/default/grub"
fi

# 3. Clean Package Cache
echo "--- Cleaning APT Cache ---"
apt clean
apt autoremove -y

# 4. Clear Log Files
echo "--- Clearing Log Files ---"
# Truncate all log files in /var/log to 0 size
find /var/log -type f -exec truncate -s 0 {} \;
# Remove archived logs
find /var/log -type f -name "*.gz" -delete
find /var/log -type f -name "*.1" -delete

# 5. Reset Machine ID (Critical)
echo "--- Resetting Machine ID ---"
truncate -s 0 /etc/machine-id
# Force the symlink for dbus machine-id
rm -f /var/lib/dbus/machine-id
ln -s /etc/machine-id /var/lib/dbus/machine-id

# 6. Configure Cloud-Init Datasource (Speed Up Boot)
echo "--- Configuring Cloud-Init Datasource ---"
mkdir -p /etc/cloud/cloud.cfg.d
cat > /etc/cloud/cloud.cfg.d/99-pve.cfg << EOF
datasource_list: [ NoCloud, ConfigDrive, None ]
EOF

# 6b. Configure Cloud-Init Network Renderer
echo "--- Configuring Cloud-Init Network Renderer ---"
echo "NOTE: Network interface will be eth0 (predictable names disabled)"
echo "NOTE: Network configuration (IP, DNS, etc.) should be set in Proxmox Cloud-Init tab"

# OS-specific network renderer configuration
if [[ "$ID" == "debian" ]]; then
    # Debian: Use ENI (ifupdown) renderer to work with /etc/network/interfaces
    # Configure cloud-init to use ENI renderer for Debian
    cat > /etc/cloud/cloud.cfg.d/01-network-renderer.cfg << 'EOF'
system_info:
  network:
    renderers: ['eni']
EOF

    echo "Debian: ENI renderer configured. Network settings will come from Proxmox Cloud-Init."
else
    # Ubuntu: Use netplan renderer (default, no config needed)
    echo "Ubuntu: Netplan renderer (default). Network settings will come from Proxmox Cloud-Init."
fi

# Remove any existing hardcoded network config that would override Proxmox settings
rm -f /etc/cloud/cloud.cfg.d/50-curtin-networking.cfg
echo "Removed hardcoded network config - Proxmox Cloud-Init will control network settings"

# 7. Remove Persistent Network Rules
echo "--- Removing Persistent Network Rules ---"
rm -f /etc/udev/rules.d/70-persistent-net.rules
rm -f /etc/udev/rules.d/75-persistent-net-generator.rules

# 8. Clean Network Config (OPTIMIZED)
echo "--- Cleaning Network Config ---"

if [[ "$ID" == "debian" ]]; then
    # On Debian, we use ENI renderer but keep netplan package installed
    # Just remove any existing netplan configs so cloud-init generates fresh ones
    rm -rf /etc/netplan/*.yaml 2>/dev/null || true

    # Clean any pre-existing network interfaces config (will be regenerated by cloud-init)
    # But preserve the file itself (we created it earlier as a safety net)
    if [ -f /etc/network/interfaces ]; then
        cat > /etc/network/interfaces << 'EOF'
# This file will be populated by cloud-init on first boot
# Network configuration is managed by cloud-init
source /etc/network/interfaces.d/*
EOF
    fi
else
    # On Ubuntu, remove netplan configs so they are regenerated on boot
    rm -f /etc/netplan/*.yaml
fi

# 9. Remove SSH Host Keys (Critical)
echo "--- Removing SSH Host Keys ---"
rm -f /etc/ssh/ssh_host_*

# 10. Reset Cloud-Init
echo "--- Resetting Cloud-Init ---"
cloud-init clean

# 11. Clean DHCP Leases
echo "--- Removing DHCP Leases ---"
rm -f /var/lib/dhcp/*

# 12. Clear Temporary Directories
echo "--- Cleaning Temporary Directories ---"
rm -rf /tmp/*
rm -rf /var/tmp/*

# 13. Clear Bash History
echo "--- Clearing History ---"
unset HISTFILE
rm -f /root/.bash_history
rm -f /home/*/.bash_history

echo "======================================================="
echo "Template preparation complete!"
echo "The Machine ID and SSH keys have been wiped."
echo "OS-specific network fixes applied."
echo "Predictable network names disabled (eth0 naming)."
echo "======================================================="

# Optional shutdown
if [ -t 0 ]; then
    read -p "Shutdown now to convert to template? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Shutting down in 5 seconds..."
        sleep 5
        shutdown -h now
    else
        echo "Please manually shut down the VM when ready to convert to template."
    fi
else
    echo "Running in non-interactive mode - NOT shutting down automatically."
    echo "Please manually shut down the VM when ready to convert to template."
fi